In [78]:
import numpy as np

In [79]:
x = np.array([1,2,3,4], dtype=np.int64)

x.dtype

In [80]:
x.dtype

dtype('int64')

In [81]:
x.shape

(4,)

In [82]:
m = np.random.randint(1, 9, (5,5))

In [83]:
m

array([[2, 3, 6, 2, 7],
       [8, 3, 3, 7, 2],
       [5, 5, 7, 1, 5],
       [1, 6, 2, 4, 4],
       [4, 8, 6, 8, 8]])

In [84]:
rr = m[1:4,1:5]

In [85]:
rr

array([[3, 3, 7, 2],
       [5, 7, 1, 5],
       [6, 2, 4, 4]])

In [86]:
rr.reshape(4,3)

array([[3, 3, 7],
       [2, 5, 7],
       [1, 5, 6],
       [2, 4, 4]])

In [87]:
rr.reshape(2,6)

array([[3, 3, 7, 2, 5, 7],
       [1, 5, 6, 2, 4, 4]])

In [91]:
rr.reshape(6,2)

array([[3, 3],
       [7, 2],
       [5, 7],
       [1, 5],
       [6, 2],
       [4, 4]])

In [117]:
a = np.array([[0, 1, 12], [9, 20, 11], [19, 5, 3], [13, 13, 4]])

In [121]:
a = a.T

In [ ]:
a

array([[ 0,  9, 19, 13],
       [ 1, 20,  5, 13],
       [12, 11,  3,  4]])

In [123]:

b = np.array([[2, 1, 2, 0], [0, 2, 1, 0], [0, 2, 1, 1], [0, 0, 0, 1]])

In [124]:
b = b.T

In [125]:
b

array([[2, 0, 0, 0],
       [1, 2, 2, 0],
       [2, 1, 1, 0],
       [0, 0, 1, 1]])

In [128]:
a * b

ValueError: operands could not be broadcast together with shapes (3,4) (4,4) 