In [1]:
from scipy import linalg
from scipy import optimize
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])

In [5]:
linalg.det(A)

-25.000000000000004

In [6]:
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [7]:
linalg.eig(A)

(array([10.5540456 +0.j, -0.5873064 +0.j,  4.03326081+0.j]),
 array([[-0.51686204, -0.94195144,  0.11527992],
        [-0.32845853,  0.31778071, -0.81936883],
        [-0.79054957,  0.10836468,  0.56155611]]))

In [8]:
m = np.array([[1,-1,-1,0],[-1,2,-1,-1],[-1,-1,2,-1],[0,-1,-1,1]])

In [9]:
linalg.eig(m)

(array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j]),
 array([[ 5.00000000e-01,  7.07106781e-01,  5.00000000e-01,
         -4.97179502e-02],
        [ 5.00000000e-01, -8.06646416e-17, -5.00000000e-01,
         -6.53884388e-01],
        [ 5.00000000e-01,  8.58688121e-17, -5.00000000e-01,
          7.53320289e-01],
        [ 5.00000000e-01, -7.07106781e-01,  5.00000000e-01,
         -4.97179502e-02]]))

In [10]:
m = np.array([['2', '2', '1', '0', '2'], ['4', '4', '1', '1', '2'], ['0', '1', '1', '3', '2'], ['4', '1', '2', '2', '0'], ['1', '0', '2', '4', '2']])

In [11]:
m = m.T

In [12]:
m

array([['2', '4', '0', '4', '1'],
       ['2', '4', '1', '1', '0'],
       ['1', '1', '1', '2', '2'],
       ['0', '1', '3', '2', '4'],
       ['2', '2', '2', '0', '2']], dtype='<U1')

In [13]:
linalg.inv(m)

array([[-0.6 ,  0.4 ,  1.6 , -0.6 , -0.1 ],
       [ 0.9 , -0.6 , -1.9 ,  0.4 ,  0.65],
       [-1.7 ,  1.8 ,  2.7 , -0.2 , -1.45],
       [-0.7 ,  0.8 ,  1.7 , -0.2 , -0.95],
       [ 1.4 , -1.6 , -2.4 ,  0.4 ,  1.4 ]])

In [14]:
mm = np.array([[6, 0, 3], [0, -1, 2], [12, 3, 0]])

In [15]:
linalg.det(mm)

0.0